### ISSUE TITLE
How to delete the shuffle data

### ISSUE THREAD

**Issue by thousandhu** [MemVerge/splash#26]
Hi,
I read the design doc https://docs.google.com/document/d/1kSpbBB-sDk41LeORm3-Hfr-up98Ozm5wskvB49tUhSs/edit?usp=sharing of splash. It's a great work which let spark use remote FS to store shuffle file with plugins. I only have one question that how the splash delete the shuffle files on the remote fs when spark job is killed or crashed. In the originally spark on yarn, Nodemanager will delete working datas of an app when the app finish, but i don't know who will do this work when running spark with splash.

**Comment by jealous** [comment]
Hi,

The `StorageFactory` interface has a member named `clearShuffle`.  This method is responsible for clearing up the files in the remote storage.  By default, the behavior is to clear everything in the folder returned by `StorageFactory.getShuffleFolder(appId)` when the shuffle manager is stopping and the current node is a driver.

That means we will only leak storage when the driver process exits abnormally.  In this case, the user needs to clean up the files in the remote storage by himself.  The folder is usually prefixed with the application ID.

But the plugin developer could always customize this behavior in their own implementations.

**Comment by thousandhu** [comment]
Thank you for your reply.
If the folder is prefixed with the application ID. it seams that we can deploy another service to monitor app finishe and delete those remote shuffle files.

**Comment by thousandhu** [comment]
Here is another question, i'm not sure should i open another issue or just ask it here.
splash support different storage backend. Shuffle always generate many small files which not is not friendly for HDFS. Do you have any suggestion which remote open source backend to be choose?

**Comment by jealous** [comment]
I think you can use NFS for testing.  We have a built-in storage factory that can be used in an NFS environment.  You can check the README file for some instructions.  

And I think most of the external storage systems support NFS.  

As you have discovered, shuffle generates a lot of small files.  In the reduce stage, it needs to read from the middle of a (remote) file.  HDFS normally won't have good performance.

**Comment by jealous** [comment]
Close this issue since there is no further question.
